/** Krátký katalog ISO2 cílových zemí, které ve scénáři typicky řešíme. */
export const COUNTRY_OPTIONS: Array<{ value: string; label: string }> = [
  { value: "CZ", label: "Česko" },
  { value: "SK", label: "Slovensko" },
  { value: "DE", label: "Německo" },
  { value: "AT", label: "Rakousko" },
  { value: "PL", label: "Polsko" },
  { value: "HU", label: "Maďarsko" },
  { value: "FR", label: "Francie" },
  { value: "BE", label: "Belgie" },
  { value: "NL", label: "Nizozemsko" },
  { value: "IT", label: "Itálie" },
  { value: "ES", label: "Španělsko" },
  { value: "PT", label: "Portugalsko" },
  { value: "CH", label: "Švýcarsko" },
  { value: "GB", label: "Velká Británie" },
  { value: "IE", label: "Irsko" },
  { value: "DK", label: "Dánsko" },
  { value: "SE", label: "Švédsko" },
  { value: "NO", label: "Norsko" },
  { value: "FI", label: "Finsko" },
  { value: "RO", label: "Rumunsko" },
  { value: "BG", label: "Bulharsko" },
  { value: "GR", label: "Řecko" },
  { value: "HR", label: "Chorvatsko" },
  { value: "SI", label: "Slovinsko" },
  { value: "EE", label: "Estonsko" },
  { value: "LV", label: "Lotyšsko" },
  { value: "LT", label: "Litva" },
  { value: "US", label: "USA" },
  { value: "CA", label: "Kanada" },
  { value: "MX", label: "Mexiko" },
  { value: "BR", label: "Brazílie" },
  { value: "CN", label: "Čína" },
  { value: "JP", label: "Japonsko" },
  { value: "KR", label: "Jižní Korea" },
  { value: "IN", label: "Indie" },
  { value: "AU", label: "Austrálie" },
  { value: "AE", label: "SAE" },
  { value: "TR", label: "Turecko" },
];

export function countryLabel(code: string): string {
  return COUNTRY_OPTIONS.find((c) => c.value === code)?.label ?? code;
}
