/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrasyRouteImport } from './routes/trasy'
import { Route as TestRouteImport } from './routes/test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsekIdRouteImport } from './routes/usek.$id'
import { Route as TrasaIdRouteImport } from './routes/trasa.$id'
import { Route as RulesNewRouteImport } from './routes/rules.new'
import { Route as RulesNewIndexRouteImport } from './routes/rules.new.index'
import { Route as RulesNewEditRouteImport } from './routes/rules.new.edit'

const TrasyRoute = TrasyRouteImport.update({
  id: '/trasy',
  path: '/trasy',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsekIdRoute = UsekIdRouteImport.update({
  id: '/usek/$id',
  path: '/usek/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrasaIdRoute = TrasaIdRouteImport.update({
  id: '/trasa/$id',
  path: '/trasa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewIndexRoute = RulesNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RulesNewRoute,
} as any)
const RulesNewEditRoute = RulesNewEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RulesNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/trasy': typeof TrasyRoute
  '/rules/new': typeof RulesNewRouteWithChildren
  '/trasa/$id': typeof TrasaIdRoute
  '/usek/$id': typeof UsekIdRoute
  '/rules/new/edit': typeof RulesNewEditRoute
  '/rules/new/': typeof RulesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/trasy': typeof TrasyRoute
  '/trasa/$id': typeof TrasaIdRoute
  '/usek/$id': typeof UsekIdRoute
  '/rules/new/edit': typeof RulesNewEditRoute
  '/rules/new': typeof RulesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/trasy': typeof TrasyRoute
  '/rules/new': typeof RulesNewRouteWithChildren
  '/trasa/$id': typeof TrasaIdRoute
  '/usek/$id': typeof UsekIdRoute
  '/rules/new/edit': typeof RulesNewEditRoute
  '/rules/new/': typeof RulesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test'
    | '/trasy'
    | '/rules/new'
    | '/trasa/$id'
    | '/usek/$id'
    | '/rules/new/edit'
    | '/rules/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/trasy'
    | '/trasa/$id'
    | '/usek/$id'
    | '/rules/new/edit'
    | '/rules/new'
  id:
    | '__root__'
    | '/'
    | '/test'
    | '/trasy'
    | '/rules/new'
    | '/trasa/$id'
    | '/usek/$id'
    | '/rules/new/edit'
    | '/rules/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestRoute: typeof TestRoute
  TrasyRoute: typeof TrasyRoute
  RulesNewRoute: typeof RulesNewRouteWithChildren
  TrasaIdRoute: typeof TrasaIdRoute
  UsekIdRoute: typeof UsekIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trasy': {
      id: '/trasy'
      path: '/trasy'
      fullPath: '/trasy'
      preLoaderRoute: typeof TrasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usek/$id': {
      id: '/usek/$id'
      path: '/usek/$id'
      fullPath: '/usek/$id'
      preLoaderRoute: typeof UsekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trasa/$id': {
      id: '/trasa/$id'
      path: '/trasa/$id'
      fullPath: '/trasa/$id'
      preLoaderRoute: typeof TrasaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new/': {
      id: '/rules/new/'
      path: '/'
      fullPath: '/rules/new/'
      preLoaderRoute: typeof RulesNewIndexRouteImport
      parentRoute: typeof RulesNewRoute
    }
    '/rules/new/edit': {
      id: '/rules/new/edit'
      path: '/edit'
      fullPath: '/rules/new/edit'
      preLoaderRoute: typeof RulesNewEditRouteImport
      parentRoute: typeof RulesNewRoute
    }
  }
}

interface RulesNewRouteChildren {
  RulesNewEditRoute: typeof RulesNewEditRoute
  RulesNewIndexRoute: typeof RulesNewIndexRoute
}

const RulesNewRouteChildren: RulesNewRouteChildren = {
  RulesNewEditRoute: RulesNewEditRoute,
  RulesNewIndexRoute: RulesNewIndexRoute,
}

const RulesNewRouteWithChildren = RulesNewRoute._addFileChildren(
  RulesNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestRoute: TestRoute,
  TrasyRoute: TrasyRoute,
  RulesNewRoute: RulesNewRouteWithChildren,
  TrasaIdRoute: TrasaIdRoute,
  UsekIdRoute: UsekIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
