/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrasyRouteImport } from './routes/trasy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RulesNewRouteImport } from './routes/rules.new'

const TrasyRoute = TrasyRouteImport.update({
  id: '/trasy',
  path: '/trasy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trasy': typeof TrasyRoute
  '/rules/new': typeof RulesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trasy': typeof TrasyRoute
  '/rules/new': typeof RulesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trasy': typeof TrasyRoute
  '/rules/new': typeof RulesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trasy' | '/rules/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trasy' | '/rules/new'
  id: '__root__' | '/' | '/trasy' | '/rules/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrasyRoute: typeof TrasyRoute
  RulesNewRoute: typeof RulesNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trasy': {
      id: '/trasy'
      path: '/trasy'
      fullPath: '/trasy'
      preLoaderRoute: typeof TrasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrasyRoute: TrasyRoute,
  RulesNewRoute: RulesNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
