/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SouladSTrasouRouteImport } from './routes/soulad-s-trasou'
import { Route as SituaceRouteImport } from './routes/situace'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SituaceIdRouteImport } from './routes/situace_.$id'
import { Route as RulesNewRouteImport } from './routes/rules.new'
import { Route as RulesNewIndexRouteImport } from './routes/rules.new.index'
import { Route as SouladSTrasouUsekIdRouteImport } from './routes/soulad-s-trasou_.usek.$id'
import { Route as SouladSTrasouTrasaIdRouteImport } from './routes/soulad-s-trasou_.trasa.$id'
import { Route as RulesNewEditRouteImport } from './routes/rules.new.edit'
import { Route as RulesRuleIdEditRouteImport } from './routes/rules.$ruleId.edit'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SouladSTrasouRoute = SouladSTrasouRouteImport.update({
  id: '/soulad-s-trasou',
  path: '/soulad-s-trasou',
  getParentRoute: () => rootRouteImport,
} as any)
const SituaceRoute = SituaceRouteImport.update({
  id: '/situace',
  path: '/situace',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SituaceIdRoute = SituaceIdRouteImport.update({
  id: '/situace_/$id',
  path: '/situace/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewRoute = RulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewIndexRoute = RulesNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RulesNewRoute,
} as any)
const SouladSTrasouUsekIdRoute = SouladSTrasouUsekIdRouteImport.update({
  id: '/soulad-s-trasou_/usek/$id',
  path: '/soulad-s-trasou/usek/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SouladSTrasouTrasaIdRoute = SouladSTrasouTrasaIdRouteImport.update({
  id: '/soulad-s-trasou_/trasa/$id',
  path: '/soulad-s-trasou/trasa/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesNewEditRoute = RulesNewEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => RulesNewRoute,
} as any)
const RulesRuleIdEditRoute = RulesRuleIdEditRouteImport.update({
  id: '/rules/$ruleId/edit',
  path: '/rules/$ruleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/situace': typeof SituaceRoute
  '/soulad-s-trasou': typeof SouladSTrasouRoute
  '/test': typeof TestRoute
  '/rules/new': typeof RulesNewRouteWithChildren
  '/situace/$id': typeof SituaceIdRoute
  '/rules/$ruleId/edit': typeof RulesRuleIdEditRoute
  '/rules/new/edit': typeof RulesNewEditRoute
  '/soulad-s-trasou/trasa/$id': typeof SouladSTrasouTrasaIdRoute
  '/soulad-s-trasou/usek/$id': typeof SouladSTrasouUsekIdRoute
  '/rules/new/': typeof RulesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/situace': typeof SituaceRoute
  '/soulad-s-trasou': typeof SouladSTrasouRoute
  '/test': typeof TestRoute
  '/situace/$id': typeof SituaceIdRoute
  '/rules/$ruleId/edit': typeof RulesRuleIdEditRoute
  '/rules/new/edit': typeof RulesNewEditRoute
  '/soulad-s-trasou/trasa/$id': typeof SouladSTrasouTrasaIdRoute
  '/soulad-s-trasou/usek/$id': typeof SouladSTrasouUsekIdRoute
  '/rules/new': typeof RulesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist': typeof ChecklistRoute
  '/situace': typeof SituaceRoute
  '/soulad-s-trasou': typeof SouladSTrasouRoute
  '/test': typeof TestRoute
  '/rules/new': typeof RulesNewRouteWithChildren
  '/situace_/$id': typeof SituaceIdRoute
  '/rules/$ruleId/edit': typeof RulesRuleIdEditRoute
  '/rules/new/edit': typeof RulesNewEditRoute
  '/soulad-s-trasou_/trasa/$id': typeof SouladSTrasouTrasaIdRoute
  '/soulad-s-trasou_/usek/$id': typeof SouladSTrasouUsekIdRoute
  '/rules/new/': typeof RulesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklist'
    | '/situace'
    | '/soulad-s-trasou'
    | '/test'
    | '/rules/new'
    | '/situace/$id'
    | '/rules/$ruleId/edit'
    | '/rules/new/edit'
    | '/soulad-s-trasou/trasa/$id'
    | '/soulad-s-trasou/usek/$id'
    | '/rules/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklist'
    | '/situace'
    | '/soulad-s-trasou'
    | '/test'
    | '/situace/$id'
    | '/rules/$ruleId/edit'
    | '/rules/new/edit'
    | '/soulad-s-trasou/trasa/$id'
    | '/soulad-s-trasou/usek/$id'
    | '/rules/new'
  id:
    | '__root__'
    | '/'
    | '/checklist'
    | '/situace'
    | '/soulad-s-trasou'
    | '/test'
    | '/rules/new'
    | '/situace_/$id'
    | '/rules/$ruleId/edit'
    | '/rules/new/edit'
    | '/soulad-s-trasou_/trasa/$id'
    | '/soulad-s-trasou_/usek/$id'
    | '/rules/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistRoute: typeof ChecklistRoute
  SituaceRoute: typeof SituaceRoute
  SouladSTrasouRoute: typeof SouladSTrasouRoute
  TestRoute: typeof TestRoute
  RulesNewRoute: typeof RulesNewRouteWithChildren
  SituaceIdRoute: typeof SituaceIdRoute
  RulesRuleIdEditRoute: typeof RulesRuleIdEditRoute
  SouladSTrasouTrasaIdRoute: typeof SouladSTrasouTrasaIdRoute
  SouladSTrasouUsekIdRoute: typeof SouladSTrasouUsekIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soulad-s-trasou': {
      id: '/soulad-s-trasou'
      path: '/soulad-s-trasou'
      fullPath: '/soulad-s-trasou'
      preLoaderRoute: typeof SouladSTrasouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situace': {
      id: '/situace'
      path: '/situace'
      fullPath: '/situace'
      preLoaderRoute: typeof SituaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situace_/$id': {
      id: '/situace_/$id'
      path: '/situace/$id'
      fullPath: '/situace/$id'
      preLoaderRoute: typeof SituaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new': {
      id: '/rules/new'
      path: '/rules/new'
      fullPath: '/rules/new'
      preLoaderRoute: typeof RulesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new/': {
      id: '/rules/new/'
      path: '/'
      fullPath: '/rules/new/'
      preLoaderRoute: typeof RulesNewIndexRouteImport
      parentRoute: typeof RulesNewRoute
    }
    '/soulad-s-trasou_/usek/$id': {
      id: '/soulad-s-trasou_/usek/$id'
      path: '/soulad-s-trasou/usek/$id'
      fullPath: '/soulad-s-trasou/usek/$id'
      preLoaderRoute: typeof SouladSTrasouUsekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soulad-s-trasou_/trasa/$id': {
      id: '/soulad-s-trasou_/trasa/$id'
      path: '/soulad-s-trasou/trasa/$id'
      fullPath: '/soulad-s-trasou/trasa/$id'
      preLoaderRoute: typeof SouladSTrasouTrasaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules/new/edit': {
      id: '/rules/new/edit'
      path: '/edit'
      fullPath: '/rules/new/edit'
      preLoaderRoute: typeof RulesNewEditRouteImport
      parentRoute: typeof RulesNewRoute
    }
    '/rules/$ruleId/edit': {
      id: '/rules/$ruleId/edit'
      path: '/rules/$ruleId/edit'
      fullPath: '/rules/$ruleId/edit'
      preLoaderRoute: typeof RulesRuleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RulesNewRouteChildren {
  RulesNewEditRoute: typeof RulesNewEditRoute
  RulesNewIndexRoute: typeof RulesNewIndexRoute
}

const RulesNewRouteChildren: RulesNewRouteChildren = {
  RulesNewEditRoute: RulesNewEditRoute,
  RulesNewIndexRoute: RulesNewIndexRoute,
}

const RulesNewRouteWithChildren = RulesNewRoute._addFileChildren(
  RulesNewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistRoute: ChecklistRoute,
  SituaceRoute: SituaceRoute,
  SouladSTrasouRoute: SouladSTrasouRoute,
  TestRoute: TestRoute,
  RulesNewRoute: RulesNewRouteWithChildren,
  SituaceIdRoute: SituaceIdRoute,
  RulesRuleIdEditRoute: RulesRuleIdEditRoute,
  SouladSTrasouTrasaIdRoute: SouladSTrasouTrasaIdRoute,
  SouladSTrasouUsekIdRoute: SouladSTrasouUsekIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
